FROM golang:1.13 AS builder

RUN mkdir /src/
WORKDIR /src/
COPY go.mod go.sum ./
RUN go mod download

COPY csaas.go ./
RUN go build csaas.go

FROM debian
COPY --from=builder /src/csaas /bin/
RUN apt-get update
RUN apt-get install -y cowsay
RUN rm -rf /var/lib/apt/lists/*
ENV PATH=/usr/games:/usr/bin:/bin
CMD ["/bin/csaas"]
