FROM python:3.7

RUN mkdir /src/
WORKDIR /src/
COPY requirements.txt hello-world.py ./
RUN pip install -r requirements.txt

ENV FLASK_APP=hello-world.py
CMD ["flask", "run", "-h", "0.0.0.0", "-p", "80"]
