FROM python:3.7-alpine

RUN mkdir /src/
WORKDIR /src/
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY hello-world.py ./

ENV FLASK_APP=hello-world.py
CMD ["flask", "run", "-h", "0.0.0.0", "-p", "80"]
